### ISSUE TITLE
Improvements to RoboMission

### ISSUE THREAD

**Issue by hanslarsson** [robovm/robovm-game-app#11]
I have added a new background image to be used underneath the score. Move the score to the bottom right corner b

**Comment by hanslarsson** [comment]
<img width="817" alt="skarmavbild 2015-10-16 kl 13 38 18" src="https://cloud.githubusercontent.com/assets/453051/10540839/fc89a1d0-740b-11e5-81f8-b224b7490221.png">

**Comment by hanslarsson** [comment]
If possible also add parallax effect to the milky way background :-)

**Comment by badlogic** [comment]
The background actually doesn't tile. Leaving that for a later release :)
