### ISSUE TITLE
Add launch screens and icons for iOS/Android

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm-game-app#7]
We need replacements for the graphics in the subfolders here: https://github.com/robovm/robovm-game-app/tree/master/android/res

We need replacements for the graphics in this folder: https://github.com/robovm/robovm-game-app/tree/master/ios/data Note that the images starting with `Default` need to be created in landscape mode!

**Comment by hanslarsson** [comment]
New images have been added.
