### ISSUE TITLE
Prettify current score in game app

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm-game-app#8]
![screen shot 2015-10-14 at 07 58 35](https://cloud.githubusercontent.com/assets/135765/10476175/b7c9b2d6-724b-11e5-933b-72be448ac948.png)

**Comment by hanslarsson** [comment]
Ok, What assets do you need from me?

**Comment by ntherning** [comment]
This is lower prio than the welcome screen in studio.

**Comment by hanslarsson** [comment]
New background image for the score has been created. Creating new issue for Mario to implement this in the game.
